version: '3.9'

services:
  api:
    container_name: skydio
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy    
    restart: always    

  